# Generated by Django 5.1.1 on 2024-09-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cloths', models.IntegerField()),
                ('underwear', models.IntegerField()),
                ('sportswear', models.IntegerField()),
                ('accessories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nbr_children', models.IntegerField()),
                ('career', models.CharField(max_length=100)),
                ('shopping_price', models.IntegerField()),
                ('collect_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_analyst.collectdata')),
            ],
        ),
    ]
